apiVersion: apps/v1
kind: Deployment
metadata:
  name: awsmid-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awsmid-config
  template:
    metadata:
      labels:
        app: awsmid-config
    spec:
      containers:
        - name: awsmid-config
          image: docker.io/yuhaibao/aws-awsmid-config:1.0.18
          env:
            - name: AUTHOR
              value: eureka
          ports:
            - containerPort: 7011
---
apiVersion: v1
kind: Service
metadata:
  name: awsmid-config
spec:
  ports:
    - port: 7011
      protocol: TCP
      targetPort: 7011
  type: ClusterIP
  selector:
    app: awsmid-config